USE ROLE accountadmin;

CREATE DATABASE BLENDX_HUB_DEV_DB;
CREATE SCHEMA BLENDX_HUB_DEV_DB.BLENDX_HUB_DEV_SCHEMA;

CREATE ROLE BLENDX_HUB_DEV_ROLE;

USE DATABASE BLENDX_HUB_DEV_DB;
USE SCHEMA BLENDX_HUB_DEV_SCHEMA;

CREATE OR REPLACE TAG environment COMMENT = 'Environment';
CREATE OR REPLACE TAG project COMMENT = 'Project name';
CREATE OR REPLACE TAG component COMMENT = 'Component name';

CREATE WAREHOUSE BLENDX_HUB_DEV_WH
WAREHOUSE_TYPE = STANDARD
WAREHOUSE_SIZE = MEDIUM
AUTO_SUSPEND = 600
AUTO_RESUME = FALSE
INITIALLY_SUSPENDED = FALSE
COMMENT = 'Warehouse for BlendX HUB Development';

ALTER WAREHOUSE BLENDX_HUB_DEV_WH SET TAG environment = 'development';
ALTER WAREHOUSE BLENDX_HUB_DEV_WH SET TAG project = 'blendx';
ALTER WAREHOUSE BLENDX_HUB_DEV_WH SET TAG component = 'hub';

CREATE USER BLENDX_HUB_DEV_USER
  PASSWORD = 'insert_password'
  LOGIN_NAME = 'BLENDX_HUB_DEV_USER'
  DISPLAY_NAME='BLENDX_HUB_DEV_USER'
  DEFAULT_WAREHOUSE='BLENDX_HUB_DEV_WH'
  DEFAULT_ROLE='BLENDX_HUB_DEV_ROLE';

GRANT USAGE ON WAREHOUSE BLENDX_HUB_DEV_WH TO ROLE BLENDX_HUB_DEV_ROLE;
GRANT USAGE ON DATABASE BLENDX_HUB_DEV_DB TO ROLE BLENDX_HUB_DEV_ROLE;
GRANT ALL ON DATABASE BLENDX_HUB_DEV_DB TO ROLE BLENDX_HUB_DEV_ROLE;
GRANT USAGE ON SCHEMA BLENDX_HUB_DEV_DB.BLENDX_HUB_DEV_SCHEMA TO ROLE BLENDX_HUB_DEV_ROLE;
GRANT ALL ON SCHEMA BLENDX_HUB_DEV_DB.BLENDX_HUB_DEV_SCHEMA TO ROLE BLENDX_HUB_DEV_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA BLENDX_HUB_DEV_DB.BLENDX_HUB_DEV_SCHEMA TO ROLE BLENDX_HUB_DEV_ROLE;
GRANT INSERT ON FUTURE TABLES IN SCHEMA BLENDX_HUB_DEV_DB.BLENDX_HUB_DEV_SCHEMA TO ROLE BLENDX_HUB_DEV_ROLE;
GRANT ALL ON SCHEMA BLENDX_HUB_DEV_DB.BLENDX_HUB_DEV_SCHEMA TO ROLE BLENDX_HUB_DEV_ROLE;

GRANT CREATE STAGE ON SCHEMA BLENDX_HUB_DEV_DB.BLENDX_HUB_DEV_SCHEMA TO ROLE BLENDX_HUB_DEV_ROLE;

GRANT ROLE BLENDX_HUB_DEV_ROLE TO USER BLENDX_HUB_DEV_USER;

-- Optional: Grant access to existing role (remove if not needed)
GRANT ROLE BLENDX_HUB_DEV_ROLE TO ROLE BLENDX_ROLE;

CREATE COMPUTE POOL IF NOT EXISTS BLENDX_HUB_DEV_POOL
 MIN_NODES = 1
 MAX_NODES = 3
 AUTO_SUSPEND_SECS = 300
 INSTANCE_FAMILY = CPU_X64_M;

-- Create Image Repository
USE ROLE BLENDX_HUB_DEV_ROLE;
USE WAREHOUSE BLENDX_HUB_DEV_WH;
USE DATABASE BLENDX_HUB_DEV_DB;
USE SCHEMA BLENDX_HUB_DEV_SCHEMA;
CREATE IMAGE REPOSITORY IF NOT EXISTS BLENDX_HUB_DEV_REPO;

-- Create Network Rule
CREATE NETWORK RULE BLENDX_HUB_DEV_NR
 TYPE = 'HOST_PORT'
 MODE = 'EGRESS'
 VALUE_LIST = ('0.0.0.0:443','0.0.0.0:80');

GRANT USAGE, MONITOR ON COMPUTE POOL BLENDX_HUB_DEV_POOL TO ROLE BLENDX_HUB_DEV_ROLE;


GRANT READ ON IMAGE REPOSITORY BLENDX_HUB_DEV_REPO TO ROLE BLENDX_HUB_DEV_ROLE;
GRANT WRITE ON IMAGE REPOSITORY BLENDX_HUB_DEV_REPO TO ROLE BLENDX_HUB_DEV_ROLE;
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE BLENDX_HUB_DEV_ROLE;

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION BLENDX_HUB_DEV_INTEGRATION
  ALLOWED_NETWORK_RULES = (BLENDX_HUB_DEV_NR)
  ENABLED = true;
GRANT USAGE ON INTEGRATION BLENDX_HUB_DEV_INTEGRATION TO ROLE BLENDX_HUB_DEV_ROLE;